---
title: "Chmouel's blog"
baseURL: "https://blog.chmouel.com/"
theme: "PaperMod"
languageCode: "en-GB"
defaultContentLanguage: "en"
pluralizelisttitles: false
removePathAccents: true
paginate: 10
paginatePath: "page"
rssLimit: 20
author:
  name: "Chmouel Boudjnah"
  url: "https://twitter.com/chmouel"
  avatar: "https://chmouel.com/chmouel.png"

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  defaultTheme: auto
  # disableThemeToggle: true
  # ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: true
  # label:
  #   icon: logo/chmouel.png
  #   iconHeight: 40

  editPost:
    URL: "https://github.com/chmouel/blog/tree/main/content"
    Text: "Edit"
    appendFilePath: true

markup:
  highlight:
    style: dracula
    lineNumbersInTable: false
    tabWidth: 2
    guessSyntax: true

menus:
  main:
    - name: "Photos"
      url: "https://photos.chmouel.com"
    - name: "Github"
      url: "https://github.com/chmouel/"
    - name: "Twitter"
      url: "https://twitter.com/chmouel"
    - name: "Strava"
      url: "https://app.strava.com/athletes/126695"
